# Generated by Django 5.1.5 on 2025-01-22 07:57

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_age',
            field=models.IntegerField(validators=[crud.models.validate_emp_age]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=100, validators=[crud.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='employeechildren',
            name='child_age',
            field=models.IntegerField(validators=[crud.models.validate_child_age]),
        ),
        migrations.AlterField(
            model_name='employeechildren',
            name='child_name',
            field=models.CharField(max_length=100, validators=[crud.models.validate_name]),
        ),
    ]
