# Generated by Django 5.1.5 on 2025-01-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_employee_emp_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='emp_email',
        ),
    ]
