# Generated by Django 5.1.5 on 2025-01-22 10:51

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_email_employee_emp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(max_length=10, validators=[crud.models.validate_emp_gender]),
        ),
    ]
