# Generated by Django 5.1.5 on 2025-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_employeechildren_child_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_age',
            field=models.IntegerField(),
        ),
    ]
