# Generated by Django 5.1.5 on 2025-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_employee_emp_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeechildren',
            name='child_age',
            field=models.IntegerField(),
        ),
    ]
